import localFont from 'next/font/local'
import { ToastContainer } from 'react-toastify'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import 'react-toastify/dist/ReactToastify.css'
import './../styles/globals.css'
import './../styles/styles.css'

const geistSans = localFont({
    src: './../public/font/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './../public/font/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})
const aardc = localFont({
    src: './../public/font/aardc.woff',
    variable: '--font-aardc',
    weight: '100 900',
})
export const metadata = {
    title: 'ATCC',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="pt-br">
            <body className={`${geistSans.variable} ${geistMono.variable} ${aardc.variable}`}>
                <ToastContainer />
                {children}
            </body>
        </html>
    )
}
